using Domain.Entities;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace DataAccess.Extensions
{
   public static class ModelBuilderExtensions
   {
      public static void SeedCategories(this ModelBuilder modelBuilder)
      {
         modelBuilder.Entity<Category>().HasData(new List<Category>
         {
            Category.Create("Abbey (Abbaye, Abdji) beer",
               "Belgian family of strong, fruity-tasting ales. Some Benedictine and Nobertine abbeys licence commercial brewers to produce these beers for them.Such products are inspired by those of the authentic Trappist monastery brewers."),
            Category.Create("Altbier",
               "German style of beer similar to British bitter or pale ale. Especially associated with Dusseldorf."),
            Category.Create("Biere de garde", "Strong, ale-like style, originally brewed to be laid down. Typical in northwest of France"),
            Category.Create("Bitter", "Implies a well hopped ale."),
            Category.Create("ESB", "Extra Special Bitter. In Britain, a specific beer from the Fuller's brewery. Has inspired many similar beers in North America"),
            Category.Create("Imperial stout", "Extra-strong stout, originally popular in Imperial Russia."),
            Category.Create("IPA", "Indian Pale Ale. Type of ale originally made for the Indian Empire. Should be above average in both hop bitterness and alcohol content."),
            Category.Create("Irish ale", "Typically has a reddish colour and a malt accent. It sometimes has a suggestion of butterscotch."),
            Category.Create("Kellerbier", "\"Cellar beer\" in German. It is usually an unfiltered lager, high in hop and low in carbonation."),
            Category.Create("Lambic", "Belgian fermented beers with wild yeasts."),
            Category.Create("Marzenbier", "Traditionally, a beer brewed in March and matured until September or October. In Germany and US, usually implies a reddish-bronze, aromatically malty, medium-strong (around 5.5abv/4.4w or more) lager."),
            Category.Create("Munich-style", "Typically a malt accented lager of conventional strength, whether pale (Helles) or dark (Dunkel)"),
            Category.Create("Geuze", "Young and old lambics, blended to achieve a sparkling, champagne-like beer."),
            Category.Create("Old ale", "Usually dark and classically medium-strong (around 6.0abv/4.8w). Some are much stronger"),
            Category.Create("Pale ale", "Originally a British style. Classically ranges from bronze to a full copper colour. \"Pale\" as opposed to a brown ale or porter."),
            Category.Create("Pils/Plilsner/Pilsener", "Widely misused term. A Pilsner is more than just a standard golden lager of around 4.25-5.25abv/3.4-4.2w. It should be an all-malt brew, with a pronounced, flowery hop aroma and dryness, typically using the Saaz variety. The original is Pilsner Urquell"),
            Category.Create("Porter", "Dark brown or black. Made with highly-kilned malts, with a good hop balance, and traditionally top-fermenting. Traditionally associated with London."),
            Category.Create("Red ale", "Like the Irish ale."),
            Category.Create("Saison", "Style of dry, sometimes slightly sour, refreshing, but strongish (5.0-8.0abv/4.0-6.4w) summer ale, often bottle-conditioned. Typical in the province of Hainault, Belgium."),
            Category.Create("Schwarzbier", "\"Black\" beer. Usually a very dark lager with a bitter-chocolate character. Especially associated with Thuringia and the former East Germany."),
            Category.Create("Scotch ale", "Smooth, malty style classically made in Scotland. Often dark, sometimes strong."),
            Category.Create("Stout", "Dark brown to black. Made with highly-roasted grains and traditionally top-fermenting. Sweet stouts are historically associated with London, hoppier dry examples with Dublin and Cork."),
            Category.Create("Trappist", "Strong ales of great character made in several monasteries in Belgium. Labels include a logo saying \"Authentic Trappist\"."),
            Category.Create("Tripel/Triple", "Usually an extra-strong, golden, aromatic hoppy golden ale, modelled on Westmalle Tripel."),
            Category.Create("Vienna-style lager", "Bronze-to-red lager with a sweetish malt aroma and flavour. No longer readily available in its city of origin, but increasingly made in the US. The Marzen-Oktoberfest type is a stronger version."),
            Category.Create("Weisse/Weissbier", "Wheat beer, pale head and often a cloudy brew.")
         });
      }

      //public static void SeedCountries(this ModelBuilder modelBuilder)
      //{
      //   modelBuilder.Entity<Country>().HasData(new List<Country>
      //   {
      //      Country.Create("Afghanistan", "af"),
      //      Country.Create("Aland Islands", "ax"),
      //      Country.Create("Albania", "al"),
      //      Country.Create("Algeria", "dz"),
      //      Country.Create("American Samoa", "as"),
      //      Country.Create("Andorra", "ad"),
      //      Country.Create("Angola", "ao"),
      //      Country.Create("Anguilla", "ai"),
      //      Country.Create("Antigua", "ag"),
      //      Country.Create("Argentina", "ar"),
      //      Country.Create("Armenia", "am"),
      //      Country.Create("Aruba", "aw"),
      //      Country.Create("Australia", "au"),
      //      Country.Create("Austria", "at"),
      //      Country.Create("Azerbaijan", "az"),
      //      Country.Create("Bahamas", "bs"),
      //      Country.Create("Bahrain", "bh"),
      //      Country.Create("Bangladesh", "bd"),
      //      Country.Create("Barbados", "bb"),
      //      Country.Create("Belarus", "by"),
      //      Country.Create("Belgium", "be"),
      //      Country.Create("Belize", "bz"),
      //      Country.Create("Benin", "bj"),
      //      Country.Create("Bermuda", "bm"),
      //      Country.Create("Bhutan", "bt"),
      //      Country.Create("Bolivia", "bo"),
      //      Country.Create("Bosnia", "ba"),
      //      Country.Create("Botswana", "bw"),
      //      Country.Create("Bouvet Island", "bv"),
      //      Country.Create("Brazil", "br"),
      //      Country.Create("British Virgin Islands", "vg"),
      //      Country.Create("Brunei", "bn"),
      //      Country.Create("Bulgaria", "bg"),
      //      Country.Create("Burkina Faso", "bf"),
      //      Country.Create("Burma", "mm"),
      //      Country.Create("Burundi", "bi"),
      //      Country.Create("Caicos Islands", "tc"),
      //      Country.Create("Cambodia", "kh"),
      //      Country.Create("Cameroon", "cm"),
      //      Country.Create("Canada", "ca"),
      //      Country.Create("Cape Verde", "cv"),
      //      Country.Create("Cayman Islands", "ky"),
      //      Country.Create("Central African Republic", "cf"),
      //      Country.Create("Chad", "td"),
      //      Country.Create("Chile", "cl"),
      //      Country.Create("China", "cn"),
      //      Country.Create("Christmas Island", "cx"),
      //      Country.Create("Cocos Islands", "cc"),
      //      Country.Create("Colombia", "co"),
      //      Country.Create("Comoros", "km"),
      //      Country.Create("Congo", "cd"),
      //      Country.Create("Congo Brazzaville", "cg"),
      //      Country.Create("Cook Islands", "ck"),
      //      Country.Create("Costa Rica", "cr"),
      //      Country.Create("Cote Divoire", "ci"),
      //      Country.Create("Croatia", "hr"),
      //      Country.Create("Cuba", "cu"),
      //      Country.Create("Cyprus", "cy"),
      //      Country.Create("Czech Republic", "cz"),
      //      Country.Create("Denmark", "dk"),
      //      Country.Create("Djibouti", "dj"),
      //      Country.Create("Dominica", "dm"),
      //      Country.Create("Dominican Republic", "do"),
      //      Country.Create("Ecuador", "ec"),
      //      Country.Create("Egypt", "eg"),
      //      Country.Create("El Salvador", "sv"),
      //      Country.Create("Equatorial Guinea", "gq"),
      //      Country.Create("Eritrea", "er"),
      //      Country.Create("Estonia", "ee"),
      //      Country.Create("Ethiopia", "et"),
      //      Country.Create("Europeanunion", "eu"),
      //      Country.Create("Falkland Islands", "fk"),
      //      Country.Create("Faroe Islands", "fo"),
      //      Country.Create("Fiji", "fj"),
      //      Country.Create("Finland", "fi"),
      //      Country.Create("France", "fr"),
      //      Country.Create("French Guiana", "gf"),
      //      Country.Create("French Polynesia", "pf"),
      //      Country.Create("French Territories", "tf"),
      //      Country.Create("Gabon", "ga"),
      //      Country.Create("Gambia", "gm"),
      //      Country.Create("Georgia", "ge"),
      //      Country.Create("Germany", "de"),
      //      Country.Create("Ghana", "gh"),
      //      Country.Create("Gibraltar", "gi"),
      //      Country.Create("Greece", "gr"),
      //      Country.Create("Greenland", "gl"),
      //      Country.Create("Grenada", "gd"),
      //      Country.Create("Guadeloupe", "gp"),
      //      Country.Create("Guam", "gu"),
      //      Country.Create("Guatemala", "gt"),
      //      Country.Create("Guinea", "gn"),
      //      Country.Create("Guinea-Bissau", "gw"),
      //      Country.Create("Guyana", "gy"),
      //      Country.Create("Haiti", "ht"),
      //      Country.Create("Heard Island", "hm"),
      //      Country.Create("Honduras", "hn"),
      //      Country.Create("Hong Kong", "hk"),
      //      Country.Create("Hungary", "hu"),
      //      Country.Create("Iceland", "is"),
      //      Country.Create("India", "in"),
      //      Country.Create("Indian Ocean Territory", "io"),
      //      Country.Create("Indonesia", "id"),
      //      Country.Create("Iran", "ir"),
      //      Country.Create("Iraq", "iq"),
      //      Country.Create("Ireland", "ie"),
      //      Country.Create("Israel", "il"),
      //      Country.Create("Italy", "it"),
      //      Country.Create("Jamaica", "jm"),
      //      Country.Create("Jan Mayen", "sj"),
      //      Country.Create("Japan", "jp"),
      //      Country.Create("Jordan", "jo"),
      //      Country.Create("Kazakhstan", "kz"),
      //      Country.Create("Kenya", "ke"),
      //      Country.Create("Kiribati", "ki"),
      //      Country.Create("Kuwait", "kw"),
      //      Country.Create("Kyrgyzstan", "kg"),
      //      Country.Create("Laos", "la"),
      //      Country.Create("Latvia", "lv"),
      //      Country.Create("Lebanon", "lb"),
      //      Country.Create("Lesotho", "ls"),
      //      Country.Create("Liberia", "lr"),
      //      Country.Create("Libya", "ly"),
      //      Country.Create("Liechtenstein", "li"),
      //      Country.Create("Lithuania", "lt"),
      //      Country.Create("Luxembourg", "lu"),
      //      Country.Create("Macau", "mo"),
      //      Country.Create("Macedonia", "mk"),
      //      Country.Create("Madagascar", "mg"),
      //      Country.Create("Malawi", "mw"),
      //      Country.Create("Malaysia", "my"),
      //      Country.Create("Maldives", "mv"),
      //      Country.Create("Mali", "ml"),
      //      Country.Create("Malta", "mt"),
      //      Country.Create("Marshall Islands", "mh"),
      //      Country.Create("Martinique", "mq"),
      //      Country.Create("Mauritania", "mr"),
      //      Country.Create("Mauritius", "mu"),
      //      Country.Create("Mayotte", "yt"),
      //      Country.Create("Mexico", "mx"),
      //      Country.Create("Micronesia", "fm"),
      //      Country.Create("Moldova", "md"),
      //      Country.Create("Monaco", "mc"),
      //      Country.Create("Mongolia", "mn"),
      //      Country.Create("Montenegro", "me"),
      //      Country.Create("Montserrat", "ms"),
      //      Country.Create("Morocco", "ma"),
      //      Country.Create("Mozambique", "mz"),
      //      Country.Create("Namibia", "na"),
      //      Country.Create("Nauru", "nr"),
      //      Country.Create("Nepal", "np"),
      //      Country.Create("Netherlands", "nl"),
      //      Country.Create("Netherlandsantilles", "an"),
      //      Country.Create("New Caledonia", "nc"),
      //      Country.Create("New Guinea", "pg"),
      //      Country.Create("New Zealand", "nz"),
      //      Country.Create("Nicaragua", "ni"),
      //      Country.Create("Niger", "ne"),
      //      Country.Create("Nigeria", "ng"),
      //      Country.Create("Niue", "nu"),
      //      Country.Create("Norfolk Island", "nf"),
      //      Country.Create("North Korea", "kp"),
      //      Country.Create("Northern Mariana Islands", "mp"),
      //      Country.Create("Norway", "no"),
      //      Country.Create("Oman", "om"),
      //      Country.Create("Pakistan", "pk"),
      //      Country.Create("Palau", "pw"),
      //      Country.Create("Palestine", "ps"),
      //      Country.Create("Panama", "pa"),
      //      Country.Create("Paraguay", "py"),
      //      Country.Create("Peru", "pe"),
      //      Country.Create("Philippines", "ph"),
      //      Country.Create("Pitcairn Islands", "pn"),
      //      Country.Create("Poland", "pl"),
      //      Country.Create("Portugal", "pt"),
      //      Country.Create("Puerto Rico", "pr"),
      //      Country.Create("Qatar", "qa"),
      //      Country.Create("Reunion", "re"),
      //      Country.Create("Romania", "ro"),
      //      Country.Create("Russia", "ru"),
      //      Country.Create("Rwanda", "rw"),
      //      Country.Create("Saint Helena", "sh"),
      //      Country.Create("Saint Kitts and Nevis", "kn"),
      //      Country.Create("Saint Lucia", "lc"),
      //      Country.Create("Saint Pierre", "pm"),
      //      Country.Create("Saint Vincent", "vc"),
      //      Country.Create("Samoa", "ws"),
      //      Country.Create("San Marino", "sm"),
      //      Country.Create("Sandwich Islands", "gs"),
      //      Country.Create("Sao Tome", "st"),
      //      Country.Create("Saudi Arabia", "sa"),
      //      Country.Create("Scotland", "gb sct"),
      //      Country.Create("Senegal", "sn"),
      //      Country.Create("Serbia", "cs"),
      //      Country.Create("Serbia", "rs"),
      //      Country.Create("Seychelles", "sc"),
      //      Country.Create("Sierra Leone", "sl"),
      //      Country.Create("Singapore", "sg"),
      //      Country.Create("Slovakia", "sk"),
      //      Country.Create("Slovenia", "si"),
      //      Country.Create("Solomon Islands", "sb"),
      //      Country.Create("Somalia", "so"),
      //      Country.Create("South Africa", "za"),
      //      Country.Create("South Korea", "kr"),
      //      Country.Create("Spain", "es"),
      //      Country.Create("Sri Lanka", "lk"),
      //      Country.Create("Sudan", "sd"),
      //      Country.Create("Suriname", "sr"),
      //      Country.Create("Swaziland", "sz"),
      //      Country.Create("Sweden", "se"),
      //      Country.Create("Switzerland", "ch"),
      //      Country.Create("Syria", "sy"),
      //      Country.Create("Taiwan", "tw"),
      //      Country.Create("Tajikistan", "tj"),
      //      Country.Create("Tanzania", "tz"),
      //      Country.Create("Thailand", "th"),
      //      Country.Create("Timorleste", "tl"),
      //      Country.Create("Togo", "tg"),
      //      Country.Create("Tokelau", "tk"),
      //      Country.Create("Tonga", "to"),
      //      Country.Create("Trinidad", "tt"),
      //      Country.Create("Tunisia", "tn"),
      //      Country.Create("Turkey", "tr"),
      //      Country.Create("Turkmenistan", "tm"),
      //      Country.Create("Tuvalu", "tv"),
      //      Country.Create("U.A.E.", "ae"),
      //      Country.Create("Uganda", "ug"),
      //      Country.Create("Ukraine", "ua"),
      //      Country.Create("United Kingdom", "gb"),
      //      Country.Create("United States", "us"),
      //      Country.Create("Uruguay", "uy"),
      //      Country.Create("US Minor Islands", "um"),
      //      Country.Create("US Virgin Islands", "vi"),
      //      Country.Create("Uzbekistan", "uz"),
      //      Country.Create("Vanuatu", "vu"),
      //      Country.Create("Vatican City", "va"),
      //      Country.Create("Venezuela", "ve"),
      //      Country.Create("Vietnam", "vn"),
      //      Country.Create("Wales", "gb wls"),
      //      Country.Create("Wallis and Futuna", "wf"),
      //      Country.Create("Western Sahara", "eh"),
      //      Country.Create("Yemen", "ye"),
      //      Country.Create("Zambia", "zm"),
      //      Country.Create("Zimbabwe", "zw")
      //   });
      //}

      //public static void SeedColors(this ModelBuilder modelBuilder)
      //{
      //   modelBuilder.Entity<Color>().HasData(new List<Color>
      //   {
      //      new Color("Black"),
      //      new Color("Brown"),
      //      new Color("Orange"),
      //      new Color("Red"),
      //      new Color("White"),
      //      new Color("Blond")
      //   });
      //}

      //public static void SeedFlavours(this ModelBuilder modelBuilder)
      //{
      //   modelBuilder.Entity<Flavour>().HasData(new List<Flavour>
      //   {
      //      new Flavour("Acidity",
      //         "An appetizing acidity, sometimes lemony, comes from hops. A fruity acidity derives from the yeast in fermentation, especially in ales and even more so in Berliner Weisse, Belgian lambic styles, and Flemish brown and red ales."),
      //      new Flavour("Apples", "A fresh, delicate, pleasant, dessert-apple character arises from the fermentation process in some English ales, famously Marstons. A more astringent, green-apple taste can arise from insufficient maturation."),
      //      new Flavour("Bananas", "Very appropriate in some South German wheat beers."),
      //      new Flavour("Bitterness", "Sounds negative, but it is positive. \"Good\" bitterness comes from the hop. It is present to varying degrees in all beers, and especially appropriate in a British bitter. Robust bitterness, as in Anchor Liberty Ale, is appetizing. Astringency is not."),
      //      new Flavour("Body", "Not actually a taste, but a sensation of texture or \"mouth feel\", ranging from thin to firm to syrupy. Thinness may mean a beer has been very fully fermented, perhaps to create a light, quenching character. Firm, textured, or grainy beers have been mashed at high temperatures to create some unfermentable sugars. Syrupy ones have been made from high density of malts, possibly with some holding back of fermentation."),
      //      new Flavour("Bubble-gum", "Very appropriate in some South German wheat beers. Arises from compounds called guaiacols created in fermentation."),
      //      new Flavour("Burnt", "Pleasant burnt flavours arise from highly kilned barley or malt in some stouts. Burnt plastic, deriving from excessive phenol, is a defect caused by yeast problems."),
      //      new Flavour("Butterscotch", "Very appropriate in certain British ales, especially some from the north of England and Scotland. Unpleasant in lagers. This flavour derives from a compound called diacetyl created in fermentation."),
      //      new Flavour("Caramel", "Most often a malt characteristic, though brewers do sometimes also add caramel itself. A malty caramel character is positive in restrained form in many types of beers. Too much can be overwhelming."),
      //      new Flavour("Cedary", "A hop character."),
      //      new Flavour("Chocolatey", "A malt character in some brown ales, porters and stouts. Typically arising from chocolate malt."),
      //      new Flavour("Cloves", "Very appropriate in some South German wheat beers. Arises from phenols created in fermentation."),
      //      new Flavour("Coffeeish", "A malt character in some dark lagers, brown ales, porters, and stouts."),
      //      new Flavour("Cookie-like", "Typical character of pale malt. Suggests a fresh beer with a good malt character."),
      //      new Flavour("Earthy", "Typical character of traditional English hops. Positive characteristic in British ales."),
      //      new Flavour("Fresh bread", "See Cookie-like."),
      //      new Flavour("Grapefruit", "Typical character of American hops, especially the Cascade variety."),
      //      new Flavour("Grass/Hay", "Can be a hop characteristic. Fresh, new-mown hat is typical in some classic European lagers. It arises from a compound called dimethyl sulphide, caused by fermentation with traditional lager yeasts."),
      //      new Flavour("Herbal", "Hop characteristic. Examples of herbal flavours are bay leaves, mint and spearmint."),
      //      new Flavour("Hoppy", "Herbal, zesty, earthy, cedary, piney, appetizingly bitter."),
      //      new Flavour("Licorice", "A characteristic of some dark malts, in German Schwarzbier, English old ales, porters, and stouts. In the English-speaking world, licorice itself is sometimes use as an addictive."),
      //      new Flavour("Madeira", "Caused by oxidation. In very strong bottle-conditioned beers that have been aged many years, this will be in a pleasant balance. In another type of beer, it is likely to be unpleasant."),
      //      new Flavour("Malty", "See Cookie-like, fresh bread, nuts, tea, toast, and toffee."),
      //      new Flavour("Minty", "Hop characteristic, especially spearmint."),
      //      new Flavour("Nuts", "Typical malt characteristic in many types of beer, especially northern English brown ales. Arises from chrystal malt."),
      //      new Flavour("Orangey", "Typical of several hop varieties. Can also arise from some ale yeasts. Positive if not overwhelming."),
      //      new Flavour("Pears", "Yeast characteristic in some ales. If overwhelming, suggest that the beer has lost some balancing hop due to age."),
      //      new Flavour("Pepper", "The flavour of alcohol. Suggest a strong beer."),
      //      new Flavour("Piney", "Characteristic of some hops, especially American varieties."),
      //      new Flavour("Plums", "Yeast character, found in South German wheat beers."),
      //      new Flavour("Raisiny", "Typical in beers made with very dark malts and to a high alcohol content, for example, imperial stouts. This flavour develops in fermentation."),
      //      new Flavour("Resiny", "Typical hop characteristic"),
      //      new Flavour("Roses", "Can arise from hops. Also from yeast development during bottle-conditioning, especially in some Belgian beers."),
      //      new Flavour("Sherry", "Dry, fino sherry flavours are typical in Belgian lambic beers. Sweet sherry can arise in strong, bottle-conditioned beers that have been aged. See also Madeira"),
      //      new Flavour("Smoky", "Appropriate in \"malt whisky beer\", smoked beer, and some dry stouts."),
      //      new Flavour("Sour", "Appropriate in Berliner Weisse, lambic, or Flemish brown or red specialities, but not in other styles of beers."),
      //      new Flavour("Strawberries", "In extremely restrained form, and in balance with malt and hop, an appropriate fermentation characteristic in some British ales."),
      //      new Flavour("Tea", "A strongish tea, of the type made in England (Indian, especially Darjeeling, with milk) is a good aroma metaphor for malt."),
      //      new Flavour("Toast", "Malt characteristic in some dark ales, porters, and stouts."),
      //      new Flavour("Tobacco", "Fragrant tobacco smoke can be evoked by the Tettnang hop, grown near Lake Constance in Germany and used in many lagers."),
      //      new Flavour("Toffee", "Malt characteristic, especially in Vienna-style, Marzen, and Oktoberfest amber lagers. Very appetizing if not overwhelming."),
      //      new Flavour("Vinegary", "See Acidity"),
      //      new Flavour("Winey", "Typical of lambic and some other Belgian styles aged in wood."),
      //      new Flavour("Yeast", "The aroma of fresh yeast, like bread rising, is typical of some ales. Can appear as a \"bite\" in some from Yorkshire, England.")
      //   });
      //}
   }
}
