CREATE TABLE [dbo].[Color]
(
	[Id] INT IDENTITY(1, 1) NOT NULL, 
    [UId] UNIQUEIDENTIFIER NOT NULL DEFAULT (newid()), 
    [Name] NVARCHAR(50) NOT NULL,
    CONSTRAINT [PK_Color] PRIMARY KEY CLUSTERED ([Id] ASC)
)
